import Head from "next/head";
import { useState } from "react";
import { ButtonBase, TextInputBase } from "@reusejs/react";

export default function Home() {
 

  const [data , setData] = useState("")
  const [list , setList] = useState<string[]>([]);
  const handleSubmit = () =>{
    setList([...list,data])
    setData("")
  }

  const handleChange = (value:any) => {
    setData(value)
  }
  console.log(list);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className='w-full flex justify-center align-middle items-center'>hello good to see you</div> */}
      <main className="flex justify-center align-middle items-center">
        <div className=" w-4/5 flex flex-col  justify-center pt-10 items-center">
          <TextInputBase
            htmlFor="price"
            labelBaseProps={{
              label: "",
            }}
            textInputBaseClasses={{
              font: "h-11 text-md text-gray-600",
              border: " border-gray-400 border-2 rounded-md",
              borderRadius: " raounded-md",
              padding: "pl-6",
              width: "w-full",
              wrapper:"w-full"
            }}
           
            name="price"
            onChange={handleChange}
            placeholder="Type anything to append below"
            type="text"
            value={data}
          />
          <ButtonBase label="Add to List" variant="indigo" onClick={handleSubmit}/>
          <div className="w-full h-96 mt-10 border-2 border-gray-400 rounded-md pt-6">
          {
            list?.map((item,index) =>
            <li className="ml-4 text-xl text-teal-900 list-squire pt-1" key={index}>{item}</li>
          )
          }
        </div>
        </div>
        
      </main>
    </>
  );
}
